name: Automate Actions for App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13, x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: npm install, npm build
      run: |
        cd app/
        npm install && npm run build

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build and Publish to S3
      run: |
        cd app/
        ng build --prod
        aws s3 sync dist/BuggetBoard-App/ ${{ secrets.S3_BUCKET_BUGGETBOARD }}
