name: Automate Actions for App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13, x]

    steps:
    - name: Checkout Repo
    - uses: actions/checkout@v2

    - name: npm install, npm build
      run: |
        cd app/
        npm install && npm run build

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy
      run: |
        cd app/
        npm run aws-deploy
