name: Automate Actions for App

on:
  push:
    branches:
      - master

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13, x]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: chrislennon/action-aws-cli@v1.1

    # - name: Node $
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: $

    - name: npm install, npm build
      run: |
        cd app/
        npm install && npm run build

    - name: deploy
      run: |
        cd app/
        npm run aws-deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
