name: Automate Actions for App

on:
  push:
    branches:
      - master

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13, x]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # - name: Node $
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: $

    - name: npm install, npm build
      run: |
        cd app/
        npm run build

    - name: deploy
      run: |
        cd app/
        npm run aws-deploy
